### ISSUE TITLE
Invalid Template Name

### ISSUE THREAD

**Issue by revzn** [dkundel/create-project#3]
i get that error:

C:\Users\Dimitri\cli>create-project typescript --git --install
ERROR Invalid template name

**Comment by dreamyguy** [comment]
@revzn the solution is probably here https://github.com/dkundel/create-project/issues/1

**Comment by andersonAlmeida** [comment]
I was having the same problem on windows. My path got D:\D:\ after resolve so I fixed with this regex. `path.resolve(...).replace(/^(\w:\\)(\w:\\)/, '$2')`

**Comment by SeyyedKhandon** [comment]
it's been answered in https://github.com/dkundel/create-project/issues/2#issuecomment-491822814

```
const templateDir = path.resolve(
    new URL(currentFileUrl).pathname.substring(new URL(currentFileUrl).pathname.indexOf('/')+1),
    '../../templates',
    options.template.toLowerCase()
  );

```

**Comment by dkundel** [comment]
Sorry for the radio silence. I ported the fix into the repo as requested in #1 but I had to drop the `+1` in it because that turns the path from absolute to relative on Unix/macOS systems. This should still make it work in Windows but I don't have a setup to try it on yet (working on that). So please let me know if this worked :)

**Comment by mednajjar** [comment]
hello @dkundel the solution of @SeyyedKhandon work's for me, many thank's to everyone.

**Comment by tertek** [comment]
> 
> 
> Sorry for the radio silence. I ported the fix into the repo as requested in #1 but I had to drop the `+1` in it because that turns the path from absolute to relative on Unix/macOS systems. This should still make it work in Windows but I don't have a setup to try it on yet (working on that). So please let me know if this worked :)

Unfortunately, this fix for path building is not working on Windows. Still getting same error.
I am using `os.platform()` to build the paths conditionally in combination with the solution of @andersonAlmeida

    const fullPathName = new URL(import.meta.url).pathname;
    let templateDir;
    templateDir = path.resolve(
        fullPathName, 
        '../../templates', 
        options.template.toLowerCase()
    );
     // Fix path building for Windows
     if(os.platform() == 'win32') {
       templateDir = templateDir.replace(/^(\w:\\)(\w:\\)/, '$2');
     }
     options.templateDirectory = templateDir;

**Comment by emptypockets-dev** [comment]
@tertek thank you! This works. 

A quick note for those new to Node—you have to include 
```
// Require os module
const os = require('os');
```
